# Generated by Django 2.2.26 on 2022-02-10 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0007_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='webiste',
            new_name='website',
        ),
    ]
